name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-musl
    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        path: ./target/x86_64-unknown-linux-musl/release/vwap
        name: vwap