name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-musl
    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        path: ./target/release/vwap
        name: vwap