name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: ekidd/rust-musl-builder:latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        sudo chown -R rust:rust .
        cargo build --release --target=x86_64-unknown-linux-musl
    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        path: ./target/release/vwap
        name: vwap